### ISSUE TITLE
hosts好效默认没添加, 没有魔法使用不了

### ISSUE THREAD

**Issue by hulao6** [wenyikun/chat-electron-app#1]
hosts好效默认没添加, 没有魔法使用不了

**Comment by wenyikun** [comment]
可以自己添加一下，https://playai.deno.dev

**Comment by wenyikun** [comment]
> hosts好效默认没添加, 没有魔法使用不了

#2

**Comment by hulao6** [comment]
换成https://playai.deno.dev/ 可以使用了
