### ISSUE TITLE
没有魔法貌似无法用哦？

### ISSUE THREAD

**Issue by monobo1989** [wenyikun/chat-electron-app#2]
提示：User location is not supported forthe API use.

**Comment by GHOST1834** [comment]
一样

**Comment by wenyikun** [comment]
> 提示：User location is not supported forthe API use.

由于这个服务有CDN，导致有些不支持的地区中转。可以改用这个，https://playai.onetry.top

**Comment by GHOST1834** [comment]
![d3ccec9ac0048cc7f4bdfb9893cd7651](https://github.com/wenyikun/chat-electron-app/assets/125651481/e84c9f66-2094-4ffb-8d03-ac78b0b40171)
NB
